# Generated by Django 6.0.4 on 2026-04-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='portal_initial_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
