# Generated by Django 6.0.4 on 2026-05-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='staff_passports/'),
        ),
    ]
