from django.urls import path

from .views import (
    student_create,
    student_delete,
    student_detail,
    student_list,
    student_update,
    student_history,
    student_move,
    bulk_student_move,
    student_dashboard,
    student_results,
    student_cbt_history,
    student_result_download_pdf,
    student_analytics,
    student_login_slips,
    student_academic_info,
    student_reset_password,
    bulk_student_upload,
    download_student_template,
    student_create_login_account,
)

urlpatterns = [
    path("", student_list, name="student_list"),
    path("create/", student_create, name="student_create"),
    path("<int:pk>/", student_detail, name="student_detail"),
    path("<int:pk>/edit/", student_update, name="student_update"),
    path("<int:pk>/delete/", student_delete, name="student_delete"),
    path("<int:pk>/move/", student_move, name="student_move"),
    path("<int:pk>/history/", student_history, name="student_history"),
    path("bulk-move/", bulk_student_move, name="bulk_student_move"),
    path("portal/dashboard/", student_dashboard, name="students_student_dashboard"),
    path("portal/results/", student_results, name="student_results"),
    path("portal/cbt-history/", student_cbt_history, name="student_cbt_history"),
    path("portal/results/<int:result_id>/download/", student_result_download_pdf, name="student_result_download_pdf"),
    path("portal/analytics/", student_analytics, name="student_analytics"),
    path("login-slips/", student_login_slips, name="student_login_slips"),
    path("portal/academic-info/", student_academic_info, name="student_academic_info"),
    path("<int:pk>/reset-password/", student_reset_password, name="student_reset_password"),
    path("bulk-upload/", bulk_student_upload, name="bulk_student_upload"),
    path("bulk-upload/template/", download_student_template, name="download_student_template"),
    path("<int:pk>/create-login/", student_create_login_account, name="student_create_login_account"),
]