# Generated by Django 6.0.4 on 2026-04-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0001_initial'),
        ('students', '0002_studentclasshistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cbtattempt',
            unique_together={('student', 'exam')},
        ),
    ]
