# Generated by Django 6.0.4 on 2026-04-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0002_alter_cbtattempt_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtattempt',
            name='auto_submit_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cbtattempt',
            name='tab_switch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cbtattempt',
            name='was_auto_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
