# Generated by Django 6.0.4 on 2026-04-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0003_cbtattempt_auto_submit_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtexam',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
