# Generated by Django 6.0.4 on 2026-04-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0004_cbtexam_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtattempt',
            name='question_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
