# Generated by Django 6.0.4 on 2026-04-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0005_cbtattempt_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtattempt',
            name='option_order',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
