# Generated by Django 6.0.4 on 2026-04-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0006_cbtattempt_option_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtexam',
            name='attempt_rule',
            field=models.CharField(choices=[('ONE', 'One Attempt Only'), ('MULTIPLE', 'Multiple Attempts / Practice Mode')], default='ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='show_in_student_portal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
