# Generated by Django 6.0.4 on 2026-04-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0007_cbtexam_attempt_rule_cbtexam_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtquestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='cbt_questions/'),
        ),
    ]
