# Generated by Django 6.0.4 on 2026-04-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0009_cbtexam_result_score_max_cbtexam_transfer_to_result'),
        ('schools', '0006_school_shuffle_cbt_options'),
        ('students', '0002_studentclasshistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBTResultTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(max_length=10)),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('converted_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.cbtattempt')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.cbtexam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
