# Generated by Django 6.0.4 on 2026-04-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0012_questionbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtexam',
            name='question_bank_items',
            field=models.ManyToManyField(blank=True, related_name='exams', to='cbt.questionbank'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
