# Generated by Django 6.0.4 on 2026-05-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0013_cbtexam_question_bank_items_questionbank_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cbtattempt',
            unique_together=set(),
        ),
    ]
