from django.urls import path

from .views import (
    cbt_dashboard,
    cbt_exam_create,
    cbt_exam_delete,
    cbt_exam_list,
    cbt_exam_toggle_status,
    cbt_exam_update,
    cbt_question_create,
    cbt_question_delete,
    cbt_question_list,
    cbt_question_update,
    student_cbt_exam_list,
    student_cbt_exam_result,
    student_cbt_exam_start,
    student_cbt_force_submit,
    student_cbt_record_tab_switch,
    student_cbt_take_exam,
    cbt_analytics_dashboard,
    cbt_exam_attempts,
    cbt_attempt_detail,
    cbt_bulk_upload_questions,
    cbt_export_attempts_csv,
    cbt_retry_transfer,
    question_bank_list,
    question_bank_create,
    cbt_add_from_bank,
    question_bank_update,
    question_bank_delete,
    super_admin_transfer_question_bank,
    super_admin_cbt_question_manager,
)

urlpatterns = [
    path("", cbt_dashboard, name="cbt_dashboard"),
    path("exams/", cbt_exam_list, name="cbt_exam_list"),
    path("exams/create/", cbt_exam_create, name="cbt_exam_create"),
    path("exams/<int:exam_id>/edit/", cbt_exam_update, name="cbt_exam_update"),
    path("exams/<int:exam_id>/delete/", cbt_exam_delete, name="cbt_exam_delete"),
    path("exams/<int:exam_id>/toggle-status/", cbt_exam_toggle_status, name="cbt_exam_toggle_status"),

    path("exams/<int:exam_id>/questions/", cbt_question_list, name="cbt_question_list"),
    path("exams/<int:exam_id>/questions/create/", cbt_question_create, name="cbt_question_create"),
    path("questions/<int:question_id>/edit/", cbt_question_update, name="cbt_question_update"),
    path("questions/<int:question_id>/delete/", cbt_question_delete, name="cbt_question_delete"),

    path("student/exams/", student_cbt_exam_list, name="student_cbt_exam_list"),
    path("student/exams/<int:exam_id>/start/", student_cbt_exam_start, name="student_cbt_exam_start"),
    path("student/attempt/<int:attempt_id>/take/", student_cbt_take_exam, name="student_cbt_take_exam"),
    path("student/attempt/<int:attempt_id>/result/", student_cbt_exam_result, name="student_cbt_exam_result"),
    path("student/attempt/<int:attempt_id>/tab-switch/", student_cbt_record_tab_switch, name="student_cbt_record_tab_switch"),
    path("student/attempt/<int:attempt_id>/force-submit/", student_cbt_force_submit, name="student_cbt_force_submit"),
    path("analytics/", cbt_analytics_dashboard, name="cbt_analytics_dashboard"),
    path("exams/<int:exam_id>/attempts/", cbt_exam_attempts, name="cbt_exam_attempts"),
    path("attempts/<int:attempt_id>/", cbt_attempt_detail, name="cbt_attempt_detail"),
    path("exams/<int:exam_id>/bulk-upload/", cbt_bulk_upload_questions, name="cbt_bulk_upload_questions"),
    path("exams/<int:exam_id>/export/", cbt_export_attempts_csv, name="cbt_export_attempts_csv"),
    path("attempts/<int:attempt_id>/retry-transfer/", cbt_retry_transfer, name="cbt_retry_transfer"),

    path("question-bank/", question_bank_list, name="question_bank_list"),
    path("question-bank/create/", question_bank_create, name="question_bank_create"),
    path("exams/<int:exam_id>/add-from-bank/", cbt_add_from_bank, name="cbt_add_from_bank"),
    path("question-bank/<int:pk>/edit/", question_bank_update, name="question_bank_update"),
    path("question-bank/<int:pk>/delete/", question_bank_delete, name="question_bank_delete"),
    path("super-admin/transfer-question-bank/", super_admin_transfer_question_bank, name="super_admin_transfer_question_bank"),
    path("super-admin/question-manager/", super_admin_cbt_question_manager, name="super_admin_cbt_question_manager"),
]