# Generated by Django 6.0.4 on 2026-04-17 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('portal_subpath', models.CharField(max_length=100, unique=True)),
                ('allow_result_checking', models.BooleanField(default=True)),
                ('is_on_trial', models.BooleanField(default=True)),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_header_text', models.CharField(blank=True, max_length=255, null=True)),
                ('grading_mode', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('passkey_length', models.PositiveIntegerField(default=8)),
                ('enable_parent_portal', models.BooleanField(default=True)),
                ('enable_cbt', models.BooleanField(default=False)),
                ('enable_sms', models.BooleanField(default=False)),
                ('enable_email', models.BooleanField(default=False)),
                ('theme_mode', models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('primary_color', models.CharField(default='#1d4ed8', max_length=20)),
                ('secondary_color', models.CharField(default='#0f172a', max_length=20)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='schools.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
