# Generated by Django 6.0.4 on 2026-04-22 15:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_subscription_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='online_payment_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='payment_method',
            field=models.CharField(choices=[('OFFLINE', 'Offline / Physical Payment'), ('ONLINE', 'Online Payment')], default='OFFLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='trial_start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SchoolSubscriptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('OFFLINE', 'Offline / Physical Payment'), ('ONLINE', 'Online Payment')], max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_start_date', models.DateField()),
                ('subscription_end_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_records', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
