# Generated by Django 6.0.4 on 2026-04-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_is_subscription_active_school_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='enable_cbt',
            field=models.BooleanField(default=False),
        ),
    ]
