# Generated by Django 6.0.4 on 2026-04-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_enable_cbt'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='show_cbt_score_immediately',
            field=models.BooleanField(default=True),
        ),
    ]
