# Generated by Django 6.0.4 on 2026-04-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_show_cbt_score_immediately'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='shuffle_cbt_questions',
            field=models.BooleanField(default=True),
        ),
    ]
