# Generated by Django 6.0.4 on 2026-04-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_shuffle_cbt_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='shuffle_cbt_options',
            field=models.BooleanField(default=True),
        ),
    ]
