# Generated by Django 6.0.4 on 2026-04-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('lessons', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonnote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='scope',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('TERMLY', 'Entire Term'), ('SESSION', 'Entire Session')], default='WEEKLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lessonnote',
            unique_together={('school', 'school_class', 'subject', 'session', 'term', 'scope', 'week', 'title')},
        ),
    ]
