# Generated by Django 6.0.4 on 2026-04-27 19:10

import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lessonnote_unique_together_lessonnote_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonnote',
            name='lesson_file',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.lesson_note_upload_path, validators=[lessons.models.validate_lesson_note_file]),
        ),
    ]
